#!/usr/bin/env python3
"""Generate adapters/ and the root marketplace from spec/.

spec/ is the source of truth. Everything this script writes is generated
output: do not edit it by hand, because CI regenerates and diffs it.

Why the spec is embedded rather than linked: on install, a plugin is copied
into a local cache. A relative link such as ../SPEC.md resolves to nothing on
the user's machine, so the skill files carry the full text inline.

Usage:
    python3 tools/build.py            # write the generated tree
    python3 tools/build.py --check    # fail if the tree is out of date
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec"
PLUGIN = ROOT / "adapters" / "claude-code" / "plugins" / "context-points"
MARKETPLACE = ROOT / ".claude-plugin" / "marketplace.json"

BANNER = (
    "<!-- Generated by tools/build.py from {source}. Do not edit by hand. -->"
)

# Relative links that would dangle once the text is copied into the plugin
# cache. Every relative markdown link must appear here or the build fails.
LINK_REWRITES = {
    "estimation.md": "the `context-points-estimation` skill",
    "../CONTRIBUTING.md": (
        "https://github.com/soaresfellipe/context-points/blob/main/CONTRIBUTING.md"
    ),
}

RELATIVE_LINK = re.compile(r"\[([^\]]+)\]\((?!https?://|#)([^)]+)\)")


class BuildError(Exception):
    pass


def parse_frontmatter(text: str, path: Path) -> tuple[dict[str, str], str]:
    """Parse the small YAML subset used in spec/: flat `key: value` scalars."""
    if not text.startswith("---\n"):
        raise BuildError(f"{path}: missing frontmatter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise BuildError(f"{path}: unterminated frontmatter")
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if not line.strip():
            continue
        if ":" not in line:
            raise BuildError(f"{path}: cannot parse frontmatter line: {line!r}")
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip()
    return meta, text[end + 5 :].lstrip("\n")


def require(meta: dict[str, str], keys: list[str], path: Path) -> None:
    missing = [k for k in keys if not meta.get(k)]
    if missing:
        raise BuildError(f"{path}: frontmatter missing {', '.join(missing)}")


def rewrite_links(body: str, path: Path) -> str:
    """Replace relative links, which dangle once copied into the cache."""

    def replace(match: re.Match[str]) -> str:
        label, target = match.group(1), match.group(2)
        if target not in LINK_REWRITES:
            raise BuildError(
                f"{path}: relative link to {target!r} has no rewrite rule. "
                f"Add one to LINK_REWRITES in tools/build.py."
            )
        replacement = LINK_REWRITES[target]
        if replacement.startswith("http"):
            return f"[{label}]({replacement})"
        return replacement

    return RELATIVE_LINK.sub(replace, body)


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(frontmatter: list[tuple[str, str]], source: str, body: str) -> str:
    lines = ["---"]
    lines += [f"{k}: {yaml_quote(v)}" for k, v in frontmatter]
    lines += ["---", "", BANNER.format(source=source), "", body.rstrip(), ""]
    return "\n".join(lines)


def build() -> dict[Path, str]:
    manifest = json.loads((SPEC / "manifest.json").read_text())
    out: dict[Path, str] = {}

    # Agents, one per role.
    for path in sorted((SPEC / "roles").glob("*.md")):
        meta, body = parse_frontmatter(path.read_text(), path)
        require(meta, ["name", "model", "summary"], path)
        out[PLUGIN / "agents" / f"{meta['name']}.md"] = render(
            [
                ("name", meta["name"]),
                ("description", meta["summary"]),
                ("model", meta["model"]),
            ],
            f"spec/roles/{path.name}",
            rewrite_links(body, path),
        )

    # Commands, one per rite.
    for path in sorted((SPEC / "rites").glob("*.md")):
        meta, body = parse_frontmatter(path.read_text(), path)
        require(meta, ["name", "summary"], path)
        frontmatter = [("description", meta["summary"])]
        if meta.get("argument-hint"):
            frontmatter.append(("argument-hint", meta["argument-hint"]))
        out[PLUGIN / "commands" / f"{meta['name']}.md"] = render(
            frontmatter, f"spec/rites/{path.name}", rewrite_links(body, path)
        )

    # Skills, with the spec text embedded rather than linked.
    for skill in manifest["skills"]:
        source = SPEC / skill["source"]
        body = rewrite_links(source.read_text(), source)
        out[PLUGIN / "skills" / skill["name"] / "SKILL.md"] = render(
            [("name", skill["name"]), ("description", skill["description"])],
            f"spec/{skill['source']}",
            body,
        )

    # plugin.json, read by Claude Code when the plugin is installed.
    out[PLUGIN / ".claude-plugin" / "plugin.json"] = (
        json.dumps(
            {
                "name": manifest["name"],
                "description": manifest["description"],
                "version": manifest["version"],
                "author": manifest["author"],
                "homepage": manifest["homepage"],
                "repository": manifest["repository"],
                "license": manifest["license"],
                "keywords": manifest["keywords"],
            },
            indent=2,
        )
        + "\n"
    )

    # marketplace.json, at the fixed path Claude Code looks for at the repo root.
    out[MARKETPLACE] = (
        json.dumps(
            {
                "name": manifest["name"],
                "owner": manifest["author"],
                "metadata": {
                    "description": manifest["description"],
                    "version": manifest["version"],
                },
                "plugins": [
                    {
                        "name": manifest["name"],
                        "source": manifest["source"],
                        "description": manifest["description"],
                        "version": manifest["version"],
                        "author": manifest["author"],
                        "homepage": manifest["homepage"],
                        "license": manifest["license"],
                        "keywords": manifest["keywords"],
                        "category": "workflow",
                    }
                ],
            },
            indent=2,
        )
        + "\n"
    )

    return out


def main() -> int:
    check = "--check" in sys.argv
    try:
        files = build()
    except BuildError as exc:
        print(f"build failed: {exc}", file=sys.stderr)
        return 1

    stale: list[Path] = []
    for path, content in sorted(files.items()):
        rel = path.relative_to(ROOT)
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(rel)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {rel}")

    if check:
        if stale:
            print("out of date:", file=sys.stderr)
            for rel in stale:
                print(f"  {rel}", file=sys.stderr)
            print("\nrun: python3 tools/build.py", file=sys.stderr)
            return 1
        print(f"{len(files)} generated files are up to date")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
